language: node_js
sudo: true
before_script:
  - npm install web-component-tester
  - npm install bower
  - 'export PATH=$PWD/node_modules/.bin:$PATH'
  - bower install
branches:
  only:
    - gh-pages
    - /.*/
node_js: 4
addons:
  firefox: latest
  # Google dropped support for 32bit Linux
  # apt:
  #   sources:
  #     - google-chrome
  #   packages:
  #     - google-chrome-stable
before_install:
  # Chrome Stable
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y google-chrome-stable
script:
  - xvfb-run wct --skip-plugin sauce
  - "if [ \"${TRAVIS_PULL_REQUEST}\" = \"false\" ]; then wct --skip-plugin local --plugin sauce; fi"
